export const products = [
    {
      id: 1,
      nombre: "Alarma Residencial",
      cantidad: 50,
      precio: 150000,
      imagen:
        "https://buildgreennh.com/wp-content/uploads/2024/01/Alarm-Systems.jpg",
      proveedor: "Security Inc.",
      ubicación: "Bogotá",
      tipo: "Alarmas",
    },
    {
      id: 2,
      nombre: "Cerradura Inteligente",
      cantidad: 30,
      precio: 200000,
      imagen:
        "https://tecnonucleous.com/content/images/size/w2000/2018/09/lockly-cerradura.jpg",
      proveedor: "Smart Lock Co.",
      ubicación: "Medellín",
      tipo: "Cerraduras",
    },
    {
      id: 3,
      nombre: "Cámara de Vigilancia IP",
      cantidad: 100,
      precio: 120000,
      imagen:
        "https://www.worten.es/i/55600d91bd05ae29cfcab8efbed7f6426483451a.jpg",
      proveedor: "Vision Tech",
      ubicación: "Tulua",
      tipo: "Cámaras",
    },
    {
      id: 4,
      nombre: "Sensor de Movimiento",
      cantidad: 80,
      precio: 50000,
      imagen:
        "https://www.cotodelaguila.es/wp-content/uploads/2023/06/sensor-de-movimiento.jpg",
      proveedor: "Secure Sensors",
      ubicación: "Cali",
      tipo: "Sensores",
    },
    {
      id: 5,
      nombre: "Sirena de Alarma",
      cantidad: 60,
      precio: 80000,
      imagen: "https://www.traxco.es/media/sirena-alarma-antirrobo.jpg",
      proveedor: "Alert Sound",
      ubicación: "Pereira",
      tipo: "Alarmas",
    },
    {
      id: 6,
      nombre: "Cerradura con Acoplamiento Remolque",
      cantidad: 90,
      precio: 70000,
      imagen:
        "https://navalchicolino.com/wp-content/uploads/2023/11/girafaro-rotativo-de-fijacion-por-ventosa-1.jpg",
      proveedor: "lock OS",
      ubicación: "Bucaramanga",
      tipo: "Cerraduras",
    },
    {
      id: 7,
      nombre: "Cámara Domo PTZ",
      cantidad: 40,
      precio: 180000,
      imagen:
        "https://www.rosarioseguridad.com.ar/admin/productos/b7008b3169ff61c9c36afc8b6ac4e613.jpg",
      proveedor: "Vision Tech",
      ubicación: "Bogotá",
      tipo: "Cámaras",
    },
    {
      id: 8,
      nombre: "Kit Alarma Antirrobo",
      cantidad: 25,
      precio: 250000,
      imagen:
        "https://www.abecoseguretat.com/wp-content/uploads/2017/09/ABECO_WEB_IMG_POPUPS_TYCO_1-1.jpg",
      proveedor: "Ats larm",
      ubicación: "Manizales",
      tipo: "Alarmas",
    },
    {
      id: 9,
      nombre: "Cerradura Forte",
      cantidad: 70,
      precio: 30000,
      imagen:
        "https://www.puertasmetalicasreto.com/wp-content/uploads/2019/02/f34b625b-ec2d-4b66-8302-96617e8a9ad6.jpg",
      proveedor: "cc lock",
      ubicación: "Barranquilla",
      tipo: "Cerraduras",
    },
    {
      id: 10,
      nombre: "Cerradura Biométrica",
      cantidad: 35,
      precio: 350000,
      imagen:
        "https://images-na.ssl-images-amazon.com/images/I/812gJBtiRgL._AC_SL1500_.jpg",
      proveedor: "Biometric Locks",
      ubicación: "Cali",
      tipo: "Cerraduras",
    },
    {
      id: 11,
      nombre: "Mini Camara de Seguridad Antirrobo",
      cantidad: 20,
      precio: 90000,
      imagen:
        "https://http2.mlstatic.com/D_NQ_NP_913573-CBT45277339917_032021-O.jpg",
      proveedor: "Anti-theft mini",
      ubicación: "Medellín",
      tipo: "Cámaras",
    },
    {
      id: 12,
      nombre: "Sensor de Apertura de Puertas",
      cantidad: 120,
      precio: 30000,
      imagen:
        "https://www.zoominformatica.com/img-datos/detector-apertura-puertas.n1.jpg",
      proveedor: "Secure Sensors",
      ubicación: "Pasto",
      tipo: "Sensores",
    },
    {
      id: 13,
      nombre: "Botón de Pánico",
      cantidad: 60,
      precio: 40000,
      imagen:
        "https://komitet.kz/wp-content/uploads/2022/12/knopka-trevozhnoj-signalizacii.jpg",
      proveedor: "Safety First",
      ubicación: "Cúcuta",
      tipo: "Alarmas",
    },
    {
      id: 14,
      nombre: "Alarma Digital",
      cantidad: 50,
      precio: 130000,
      imagen:
        "https://advancedalarmandfireinc.com/wp-content/uploads/2021/09/Intrusion-Alarm-Panel-m-400x467.jpeg",
      proveedor: "Digital cp",
      ubicación: "Bogotá",
      tipo: "Alarmas",
    },
    {
      id: 15,
      nombre: "Video Portero",
      cantidad: 40,
      precio: 220000,
      imagen:
        "https://acis.org.co/portal/sites/default/files/Video%20portero%201.jpg",
      proveedor: "Comms Solutions",
      ubicación: "Medellín",
      tipo: "Intercomunicadores",
    },
    {
      id: 16,
      nombre: "Kit de Videovigilancia",
      cantidad: 30,
      precio: 500000,
      imagen:
        "https://b282c5de4f50ed30d5ce-25e9f6b52714e6c3d4dbb7e330152014.ssl.cf3.rackcdn.com/uploaded_thumb_seo/d6059241df26a595b5aa2d49b79528cb/img_7600_fbfe63988f82a02fc305877c758155c4_20.jpg",
      proveedor: "Vision Tech",
      ubicación: "Barranquilla",
      tipo: "Cámaras",
    },
    {
      id: 17,
      nombre: "Cerradura Electrónica",
      cantidad: 70,
      precio: 150000,
      imagen:
        "https://s.libertaddigital.com/2020/08/19/cerradura-inteligente-invisible-kenrod.jpg",
      proveedor: "Smart Lock Co.",
      ubicación: "Bogotá",
      tipo: "Cerraduras",
    },
    {
      id: 18,
      nombre: "Sensor Prendas",
      cantidad: 60,
      precio: 15000,
      imagen:
        "https://http2.mlstatic.com/D_NQ_NP_752563-MLU72700304589_112023-O.webp",
      proveedor: "ant Sensors",
      ubicación: "Bucaramanga",
      tipo: "Sensores",
    },
    {
      id: 19,
      nombre: "Cerradura de Puerta",
      cantidad: 80,
      precio: 75000,
      imagen:
        "https://img.tttcdn.com/product/xy/2000/2000/p/gu1/S/S/S5846S/S5846S-1-da45-ZF2C.jpg",
      proveedor: "Nw DOOR",
      ubicación: "Cali",
      tipo: "Cerraduras",
    },
    {
      id: 20,
      nombre: "Alarma Antirrobo para Autos",
      cantidad: 40,
      precio: 110000,
      imagen:
        "https://img.tttcdn.com/product/xy/2000/2000/p/gu1/K/4/K15994/K15994-1-b893-4K5h.jpg",
      proveedor: "AutoSecure",
      ubicación: "Medellín",
      tipo: "Alarmas",
    },
    {
      id: 21,
      nombre: "Cámara IP 360°",
      cantidad: 45,
      precio: 160000,
      imagen:
        "https://http2.mlstatic.com/D_NQ_NP_992706-MLC46023895219_052021-F.jpg",
      proveedor: "Vision Tech",
      ubicación: "Bogotá",
      tipo: "Cámaras",
    },
    {
      id: 22,
      nombre: "Sirena Inalámbrica",
      cantidad: 65,
      precio: 95000,
      imagen:
        "https://infotecnologiasur.cl/wp-content/uploads/2020/02/sirenayreceptor01.jpg",
      proveedor: "Alert Sound",
      ubicación: "Manizales",
      tipo: "Alarmas",
    },
    {
      id: 23,
      nombre: "Intercomunicador con Video",
      cantidad: 25,
      precio: 270000,
      imagen:
        "https://ferreteriavidri.com/images/items/large/122321.jpg?v=1662229912",
      proveedor: "Comms Solutions",
      ubicación: "Medellín",
      tipo: "Intercomunicadores",
    },
    {
      id: 24,
      nombre: "Sensor de Rotura de Cristales",
      cantidad: 70,
      precio: 55000,
      imagen:
        "https://www.tecmap.com.ar/wp-content/uploads/2019/10/drv-100-1024x1024.jpg",
      proveedor: "Secure Sensors",
      ubicación: "Cúcuta",
      tipo: "Sensores",
    },
    {
      id: 25,
      nombre: "Kit de Cámaras para Negocio",
      cantidad: 50,
      precio: 350000,
      imagen:
        "https://www.latiendainteligente.es/wp-content/uploads/2018/04/KIT-OFICINAS-de-8-camaras-de-vigilancia-con-grabacion-ppal-2-400x400.jpg",
      proveedor: "Vision Tech",
      ubicación: "Bogotá",
      tipo: "Cámaras",
    },
    {
      id: 26,
      nombre: "Cerradura con Código",
      cantidad: 80,
      precio: 180000,
      imagen:
        "https://productosintegra.com/wp-content/uploads/2022/04/cerradura-por-codigo-autonomo-con-apertura-locstar-loc-ls8015-tm.jpg",
      proveedor: "Smart Lock Co.",
      ubicación: "Cartagena",
      tipo: "Cerraduras",
    },
    {
      id: 27,
      nombre: "Cámara de Seguridad Exterior",
      cantidad: 90,
      precio: 130000,
      imagen:
        "https://s.libertaddigital.com/2021/03/10/camara-de-vigilancia-exterior-wifi-iegeek-ig62.jpg",
      proveedor: "Vision Tech",
      ubicación: "Pereira",
      tipo: "Cámaras",
    },
    {
      id: 28,
      nombre: "Sistema de Alarma Antirobo para Motos",
      cantidad: 70,
      precio: 80000,
      imagen:
        "https://comprasegura.pe/wp-content/uploads/WhatsApp-Image-2022-08-17-at-10.21.37-PM.jpeg",
      proveedor: "RTT Motorcycle",
      ubicación: "Bogotá",
      tipo: "Alarmas",
    },
    {
      id: 29,
      nombre: "Alarma para Ventanas",
      cantidad: 60,
      precio: 45000,
      imagen:
        "https://images-na.ssl-images-amazon.com/images/I/61eACDfduRL._AC_SL1200_.jpg",
      proveedor: "Window Secure",
      ubicación: "Medellín",
      tipo: "Alarmas",
    },
    {
      id: 30,
      nombre: "Cerradura con Bluetooth",
      cantidad: 50,
      precio: 220000,
      imagen:
        "https://image.made-in-china.com/2f0j00tThoPEFlYBgJ/WiFi-Tuya-Electronic-Fingerprint-Smart-Door-Lock.jpg",
      proveedor: "Smart Lock Co.",
      ubicación: "Cali",
      tipo: "Cerraduras",
    },
    {
      id: 31,
      nombre: "Sensor de Vibración",
      cantidad: 100,
      precio: 35000,
      imagen: "https://images.nexusapp.co/assets/e7/7e/21/9810172.jpg",
      proveedor: "Secure Sensors",
      ubicación: "Barranquilla",
      tipo: "Sensores",
    },
    {
      id: 32,
      nombre: "Arco detector (Antena) Sistema Antirrobo en Tiendas",
      cantidad: 80,
      precio: 75000,
      imagen: "https://http2.mlstatic.com/S_469511-MLV20576469319_022016-O.jpg",
      proveedor: "Block shoop",
      ubicación: "Pasto",
      tipo: "Detectores",
    },
    {
      id: 33,
      nombre: "Alarma con Mando a Distancia",
      cantidad: 60,
      precio: 110000,
      imagen:
        "https://www.alarmaseguridad.com/wp-content/uploads/bb7e5adafb6d.jpg",
      proveedor: "Remote Alert",
      ubicación: "Medellín",
      tipo: "Alarmas",
    },
    {
      id: 34,
      nombre: "Cámara Bullet HD",
      cantidad: 75,
      precio: 140000,
      imagen:
        "http://www.klikglodok.com/toko/36620-large_default/harga-jual-hilook-thc-b120-pc-cctv-camera-.jpg",
      proveedor: "Vision Tech",
      ubicación: "Cali",
      tipo: "Cámaras",
    },
    {
      id: 35,
      nombre: "Alarma Wiriless Home AA",
      cantidad: 120,
      precio: 30000,
      imagen:
        "https://site-473055.mozfiles.com/files/473055/catitems/Alarma_Wireless_Home_Seguridad_Antirrobo_Garage_con_Teclado_Puerta_Ventana_110dB_______AA-f52b4164568c83f7b407655ec6a75f9c.jpeg?2194378",
      proveedor: "Home Sensor Alarms",
      ubicación: "Bucaramanga",
      tipo: "Alarmas",
    },
    {
      id: 36,
      nombre: "Bloqueador De Pedal Auto",
      cantidad: 40,
      precio: 160000,
      imagen:
        "https://i5.walmartimages.com/asr/504d8714-3aa7-475a-8853-e8156ccd80c6.7c74cbc7c5052bc480029f283c22b0bc.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
      proveedor: "Car Safety lock",
      ubicación: "Manizales",
      tipo: "Cerraduras",
    },
    {
      id: 37,
      nombre: "Alarma para Puerta de Garaje",
      cantidad: 45,
      precio: 95000,
      imagen:
        "https://www.securitasdirect.es/sites/default/files/2020-09/fotodetector-garaje.jpg",
      proveedor: "Garage Secure",
      ubicación: "Cali",
      tipo: "Alarmas",
    },
    {
      id: 38,
      nombre: "Cámara con Visión Nocturna",
      cantidad: 60,
      precio: 150000,
      imagen:
        "https://i5-mx.walmartimages.com/mg/gm/3pp/asr/4d40b120-8f55-4b7d-a197-203aebba9528.4eb9c8ad713a6629d0db147d4c9c95ff.jpeg?odnHeight=2000&odnWidth=2000&odnBg=ffffff",
      proveedor: "Vision Tech",
      ubicación: "Cartagena",
      tipo: "Cámaras",
    },
    {
      id: 39,
      nombre: "Cerradura clasica",
      cantidad: 85,
      precio: 50000,
      imagen:
        "https://static.prod.cmostores.com/uploads/products/5/l/securit-security-heavy-duty-door-chain-brass-80mm-mpb1636-2.jpg?auto=format",
      proveedor: "Clasicc block",
      ubicación: "Yumbo",
      tipo: "cerraduras",
    },
    {
      id: 40,
      nombre: "Kit Antirrobo para Motocicleta",
      cantidad: 20,
      precio: 600000,
      imagen:
        "https://ae01.alicdn.com/kf/Sbba43ab596d747d8b5d9768a55b9c03dd/Kit-antirrobo-para-motocicleta-de-12V-alarma-antirrobo-autom-tica-de-1-v-a-Control-remoto.jpg",
      proveedor: "Safety motorcycle",
      ubicación: "Tulua",
      tipo: "Kits",
    },
  ];
  